### ISSUE TITLE
Strip punctuation from training input and user input

### ISSUE THREAD

**Issue by rolfbjarne** [jonathanpeppers/inclusive-code-reviews-browser#123]
It looks like our ML model gets confused when it encounters punctuation, so we should strip it from both training input and any user input we evaluate with the model.

Punctuation to remove: !?:;
Punctuation to keep: ,.

**Comment by jonathanpeppers** [comment]
Part of the problem here is this option isn't exportable to `.onnx`:

https://github.com/jonathanpeppers/inclusive-code-reviews-ml/pull/29#discussion_r944879120

I'm not sure if it would be better for us to strip them out ourselves, or contribute to ML.NET? We're using nightly builds from main, so we'd get our change pretty quick.

**Comment by jonathanpeppers** [comment]
Filed this: https://github.com/dotnet/machinelearning/issues/6317
